"""Generate the content catalog from metadata.

Reads every <ID>_metadata.json under the content directories and writes:
  - CATALOG.md               one page listing all content, grouped by type
  - <dir>/README.md          the index table for each content directory
  - catalog.json             the same data for tooling

Names, descriptions, and cross-references come from the metadata, so the
catalog cannot drift from the content. Run after adding or changing content:

  python tools/build_catalog.py           # write the files
  python tools/build_catalog.py --check   # exit 1 if any file is stale (CI)

No dependencies.
"""
import glob
import io
import json
import os
import re
import sys

# (directory, heading, intro sentence) in catalog order.
SECTIONS = (
    ("blueprints", "Blueprints",
     "Orderable resources. Each folder has a README with contents, prerequisites, and setup."),
    ("resource_actions", "Resource actions",
     "Day-2 actions on resources. Most belong to a blueprint and are documented there."),
    ("server_actions", "Server actions",
     "Day-2 actions on servers."),
    ("orchestration_actions", "Orchestration actions",
     "Lifecycle hooks. Actions marked disabled ship that way on purpose; read the README before enabling."),
    ("flowcontrol_actions", "Flow control actions",
     "ALLOW/PAUSE gates."),
    ("recurring_jobs", "Recurring jobs",
     "Cron-scheduled jobs."),
    ("cit_tests", "CIT tests",
     "Integration tests."),
    ("webhooks", "Webhooks",
     "Inbound REST endpoints."),
    ("mcp_tool_actions", "MCP tool actions",
     "Actions published as tools on CloudBolt's MCP server for AI agents to call. Each tool's "
     "inputs are its parameters; the code lives on the referenced plugin."),
    ("plugins", "Plugins",
     "Python and remote-script actions. Plugins that belong to a blueprint or action are "
     "documented in that parent's README; standalone plugins have their own."),
    ("shared_modules", "Shared modules",
     "Reusable Python libraries imported by plugins as `shared_modules.<name>`. A module syncs "
     "only with content that declares it under `dependencies.sharedModules`."),
    ("extensions", "UI extensions",
     "Django UI extensions (XUI). Each folder has a README."),
    ("forms", "Forms",
     "Custom order forms. A form syncs only as a dependency of its parent blueprint; it is not "
     "imported on its own."),
    ("form_functions", "Form functions",
     "Form JavaScript helpers. A function syncs only as a dependency of a form."),
)
CONTENT_DIRS = tuple(s[0] for s in SECTIONS)
REF_RE = re.compile(r"^(%s)/([A-Z]+-[A-Za-z0-9]+)$" % "|".join(CONTENT_DIRS))
GENERATED_NOTE = "<!-- Generated by tools/build_catalog.py from the metadata files. Edit those, not this file. -->"


class Unit:
    def __init__(self, path, meta):
        self.path = path                      # "plugins/OHK-abcd1234"
        self.dir, self.id = path.split("/")
        self.meta = meta
        self.uses = []                        # paths this unit depends on
        self.used_by = []                     # paths that depend on this unit
        self.readme = os.path.exists(os.path.join(self.dir, self.id, "README.md"))
        self.form = json.loads(meta["json"]) if self.dir == "forms" and meta.get("json") else {}

    @property
    def name(self):
        if self.dir == "forms":
            return self.form.get("title") or self.id
        if self.dir == "shared_modules":
            # The import name (shared_modules.<name>), not the display label.
            return self.meta.get("name") or self.id
        return self.meta.get("label") or self.meta.get("name") or self.id

    def description(self, units):
        if self.dir == "forms":
            text = self.form.get("description")
        else:
            text = self.meta.get("description")
        if not text and self.dir == "mcp_tool_actions":
            # Exported MCP tool actions carry no description; the tool description is the one
            # the AI agent sees.
            text = self.meta.get("mcp_tool_description")
        if not text and self.dir in ("resource_actions", "server_actions"):
            # Exported action metadata carries no description; use the plugin's.
            hook = (self.meta.get("dependencies") or {}).get("hook")
            if hook in units:
                text = units[hook].meta.get("description")
        return " ".join((text or "").split())

    def link(self, from_dir=None):
        """Markdown link to the README if present, else the folder."""
        target = self.path + ("/README.md" if self.readme else "/")
        if from_dir is None:
            return target                     # from the repo root
        if from_dir == self.dir:
            return target[len(self.dir) + 1:]  # from the same directory
        return "../" + target                 # from a sibling directory


def load_units():
    units = {}
    for path in sorted(glob.glob("*/*/*_metadata.json")):
        parts = path.replace(os.sep, "/").split("/")
        if parts[0] not in CONTENT_DIRS or parts[2] != parts[1] + "_metadata.json":
            continue
        with io.open(path, encoding="utf-8") as fh:
            meta = json.load(fh)
        key = "/".join(parts[:2])
        units[key] = Unit(key, meta)
    for unit in units.values():
        for target in sorted(set(collect_refs(unit.meta))):
            if target in units and target != unit.path:
                unit.uses.append(target)
                units[target].used_by.append(unit.path)
    for unit in units.values():
        unit.used_by.sort(key=lambda p: units[p].name.lower())
    return units


def collect_refs(obj):
    """Yield every "<dir>/<ID>" string found under any "dependencies" key."""
    if isinstance(obj, dict):
        for key, value in obj.items():
            if key == "dependencies" and isinstance(value, dict):
                for dep in value.values():
                    for item in (dep if isinstance(dep, list) else [dep]):
                        if isinstance(item, str) and REF_RE.match(item):
                            yield item
            else:
                yield from collect_refs(value)
    elif isinstance(obj, list):
        for item in obj:
            yield from collect_refs(item)


def cell(text):
    return text.replace("|", "\\|") if text else ""


def ref_cell(paths, units, from_dir, only_dirs=None, empty=""):
    names = []
    for p in paths:
        u = units[p]
        if only_dirs and u.dir not in only_dirs:
            continue
        names.append("[%s](%s)" % (cell(u.name), u.link(from_dir)))
    return ", ".join(names) or empty


def hook_cell(unit, units, from_dir):
    hook = (unit.meta.get("dependencies") or {}).get("hook")
    return ref_cell([hook], units, from_dir) if hook in units else ""


def rows_for(section_dir, members, units, from_dir):
    """Return (header, rows) for one content type."""
    d = section_dir
    if d == "blueprints":
        head = ["Blueprint", "ID", "Description"]
        rows = [[u.name, "", u.description(units)] for u in members]
    elif d == "resource_actions":
        head = ["Action", "ID", "Description", "Plugin", "Blueprint"]
        rows = [[u.name, "", u.description(units), hook_cell(u, units, from_dir),
                 ref_cell(u.used_by, units, from_dir, {"blueprints"}, "standalone")] for u in members]
    elif d == "orchestration_actions":
        head = ["Action", "ID", "Description", "Hook point", "Enabled", "Plugin"]
        rows = [[u.name, "", u.description(units), u.meta.get("hook_point") or "",
                 "yes" if u.meta.get("enabled") else "no", hook_cell(u, units, from_dir)] for u in members]
    elif d == "recurring_jobs":
        head = ["Job", "ID", "Description", "Schedule", "Plugin"]
        rows = [[u.name, "", u.description(units), "`%s`" % u.meta.get("schedule", ""),
                 hook_cell(u, units, from_dir)] for u in members]
    elif d == "mcp_tool_actions":
        head = ["Tool", "ID", "Description", "MCP tool name", "Enabled", "Plugin"]
        rows = [[u.name, "", u.description(units), "`%s`" % (u.meta.get("mcp_tool_name") or ""),
                 "yes" if u.meta.get("enabled") else "no", hook_cell(u, units, from_dir)] for u in members]
    elif d == "plugins":
        head = ["Plugin", "ID", "Description", "Type", "Used by"]
        rows = [[u.name, "", u.description(units), u.meta.get("type") or "",
                 ref_cell(u.used_by, units, from_dir, empty="standalone")] for u in members]
    elif d == "shared_modules":
        head = ["Module", "ID", "Description", "Used by"]
        rows = [["`%s`" % u.name, "", u.description(units),
                 ref_cell(u.used_by, units, from_dir, empty="unused")] for u in members]
    elif d == "extensions":
        head = ["Extension", "ID", "Description"]
        rows = [[u.name, "", u.description(units)] for u in members]
    elif d == "forms":
        head = ["Form", "ID", "Description", "Blueprint"]
        rows = [[u.name, "", u.description(units),
                 ref_cell(u.used_by, units, from_dir, {"blueprints"}, "orphan")] for u in members]
    elif d == "form_functions":
        head = ["Function", "ID", "Description", "Form"]
        rows = [[u.name, "", u.description(units),
                 ref_cell(u.used_by, units, from_dir, {"forms"}, "orphan")] for u in members]
    else:  # server_actions, flowcontrol_actions, cit_tests, webhooks
        head = ["Action", "ID", "Description", "Plugin"]
        rows = [[u.name, "", u.description(units), hook_cell(u, units, from_dir)] for u in members]
    for u, row in zip(members, rows):
        row[0] = cell(row[0])
        row[1] = "[%s](%s)" % (u.id, u.link(from_dir))
        row[2] = cell(row[2])
    return head, rows


def table(head, rows):
    lines = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


def members_of(section_dir, units):
    return sorted((u for u in units.values() if u.dir == section_dir), key=lambda u: u.name.lower())


def render(units):
    """Return {relative path: content} for every generated file."""
    out = {}
    present = [s for s in SECTIONS if os.path.isdir(s[0])]

    toc = ["| Type | Count |", "|---|---|"]
    body = []
    for d, heading, intro in present:
        members = members_of(d, units)
        anchor = heading.lower().replace(" ", "-")
        toc.append("| [%s](#%s) | %d |" % (heading, anchor, len(members)))
        head, rows = rows_for(d, members, units, from_dir=None)
        body.append("## %s\n\n%s\n\n%s" % (heading, intro, table(head, rows)))
        head, rows = rows_for(d, members, units, from_dir=d)
        out[d + "/README.md"] = "%s\n# %s\n\n%s\n\n%s\n" % (GENERATED_NOTE, heading, intro, table(head, rows))

    out["CATALOG.md"] = (
        "%s\n# Content catalog\n\n"
        "Every piece of content in this repo, grouped by type. Names and descriptions come from each "
        "folder's `<ID>_metadata.json`; links go to the folder's README. Regenerate with "
        "`python tools/build_catalog.py`.\n\n%s\n\n%s\n"
    ) % (GENERATED_NOTE, "\n".join(toc), "\n\n".join(body))

    records = []
    for u in sorted(units.values(), key=lambda u: u.path):
        rec = {
            "id": u.id,
            "type": u.dir,
            "name": u.name,
            "description": u.description(units),
            "path": u.path,
            "readme": u.path + "/README.md" if u.readme else None,
            "uses": u.uses,
            "used_by": u.used_by,
        }
        for key in ("hook_point", "enabled", "schedule"):
            if key in u.meta:
                rec[key] = u.meta[key]
        if u.dir == "plugins":
            rec["plugin_type"] = u.meta.get("type")
        if u.dir == "mcp_tool_actions":
            rec["mcp_tool_name"] = u.meta.get("mcp_tool_name")
        records.append(rec)
    out["catalog.json"] = json.dumps(records, indent=2, ensure_ascii=False) + "\n"
    return out


def main(argv):
    check = "--check" in argv
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)
    units = load_units()
    if not units:
        sys.exit("no metadata files found")
    generated = render(units)
    stale = []
    for rel, content in generated.items():
        current = None
        if os.path.exists(rel):
            with io.open(rel, encoding="utf-8", newline="") as fh:
                current = fh.read().replace("\r\n", "\n")
        if current == content:
            continue
        stale.append(rel)
        if not check:
            with io.open(rel, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(content)
    if check:
        if stale:
            print("catalog is stale; run `python tools/build_catalog.py` and commit:")
            for rel in stale:
                print("  " + rel)
            return 1
        print("catalog is up to date (%d content units)" % len(units))
        return 0
    print("wrote %d file(s) for %d content units" % (len(stale), len(units)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
